name             'cmd_lamp'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures cmd_lamp'
long_description 'Installs/Configures cmd_lamp'
version          '0.1.0'

depends 'build-essential'
depends 'apt'
depends 'git'
depends 'php'
depends 'apache2'
depends 'mysql'
depends 'composer'
depends 'nodejs'